version: '3.2'

services:

  message-queue:
    image: nats:nanoserver
    networks:
      - app-net

  signup-app:
    image: dockersamples/mta-dev-signup-app:v3
    depends_on:
      - message-queue
    networks:
      - app-net

  signup-save-handler:
    image: dockersamples/mta-dev-signup-save-handler:v1
    networks:
      - app-net